# Generated by Django 5.2.4 on 2025-07-18 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ECODE', models.IntegerField(primary_key=True, serialize=False)),
                ('FNAME', models.CharField(max_length=20)),
                ('LNAME', models.CharField(max_length=20)),
                ('DESIG', models.CharField(max_length=15)),
                ('LEVEL', models.IntegerField()),
                ('GENDER', models.CharField(default='M', max_length=1)),
                ('DOB', models.DateField()),
                ('DOJ', models.DateField()),
                ('MOB', models.CharField(max_length=11)),
                ('PAN', models.CharField(max_length=10)),
                ('ACNO', models.CharField(max_length=15)),
                ('IFSC', models.CharField(max_length=11)),
                ('BASIC', models.IntegerField()),
                ('TA', models.IntegerField()),
                ('HRAYN', models.CharField(max_length=1)),
                ('NPSYN', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Setter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAP', models.IntegerField()),
                ('HRAP', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YEAR', models.IntegerField()),
                ('MONTH', models.IntegerField()),
                ('NODAYS', models.IntegerField()),
                ('DA', models.IntegerField()),
                ('DATA', models.IntegerField()),
                ('HRA', models.IntegerField()),
                ('NPS_M', models.IntegerField()),
                ('OTHER_ALLW', models.IntegerField()),
                ('GROSS', models.IntegerField()),
                ('ITAX', models.IntegerField()),
                ('NPS_O', models.IntegerField()),
                ('GPF', models.IntegerField(default=0)),
                ('LCFEE', models.IntegerField()),
                ('ODEDUCT', models.IntegerField()),
                ('TOT_DEDUC', models.IntegerField()),
                ('NETSAL', models.IntegerField()),
                ('ECODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_app.employee')),
            ],
            options={
                'unique_together': {('YEAR', 'MONTH', 'ECODE')},
            },
        ),
    ]
