# Generated by Django 5.2.4 on 2025-07-20 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pay',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ACNO',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='GENDER',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='HRAYN',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='IFSC',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='LEVEL',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='NPSYN',
        ),
        migrations.AlterField(
            model_name='employee',
            name='BASIC',
            field=models.IntegerField(verbose_name='Basic Salary'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='DESIG',
            field=models.CharField(max_length=50, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='DOB',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='DOJ',
            field=models.DateField(verbose_name='Date of Joining'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ECODE',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Employee Code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='FNAME',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='LNAME',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='MOB',
            field=models.CharField(max_length=20, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='PAN',
            field=models.CharField(max_length=10, verbose_name='PAN Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='TA',
            field=models.IntegerField(verbose_name='Travel Allowance'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='DA',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pay',
            name='DATA',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pay',
            name='ECODE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_app.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='GPF',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pay',
            name='GROSS',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pay',
            name='HRA',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pay',
            name='ITAX',
            field=models.FloatField(verbose_name='Income Tax'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='LCFEE',
            field=models.FloatField(verbose_name='Late/Convenience Fee'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='MONTH',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pay',
            name='NETSAL',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pay',
            name='NODAYS',
            field=models.IntegerField(verbose_name='Working Days'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='NPS_M',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pay',
            name='NPS_O',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pay',
            name='ODEDUCT',
            field=models.FloatField(verbose_name='Other Deductions'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='OTHER_ALLW',
            field=models.FloatField(verbose_name='Other Allowance'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='TOT_DEDUC',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='setter',
            name='DAP',
            field=models.FloatField(verbose_name='DA Percentage'),
        ),
        migrations.AlterField(
            model_name='setter',
            name='HRAP',
            field=models.FloatField(verbose_name='HRA Percentage'),
        ),
    ]
