# Generated by Django 5.2.4 on 2025-07-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0002_alter_pay_unique_together_remove_employee_acno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='GENDER',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='employee',
            name='LEVEL',
            field=models.CharField(blank=True, max_length=20, verbose_name='Job Level'),
        ),
    ]
