# Generated by Django 5.2.4 on 2025-07-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0003_employee_gender_employee_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='EMAIL',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
    ]
