# Generated by Django 5.2.4 on 2025-07-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0004_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='YEAR',
            field=models.IntegerField(default=2025, verbose_name='Year'),
        ),
    ]
