# Generated by Django 5.2.4 on 2025-07-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0005_alter_pay_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='NODAYS',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Days Worked'),
        ),
    ]
