# Generated by Django 5.2.4 on 2025-07-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0006_alter_pay_nodays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='OTHER_ALLW',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Other Allowance'),
        ),
    ]
