# Generated by Django 5.2.4 on 2025-07-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0008_alter_pay_itax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='LCFEE',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Late/Convenience Fee'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='ODEDUCT',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Other Deductions'),
        ),
    ]
